AWSTemplateFormatVersion: "2010-09-09"
Description: Superstore
Parameters:
  EnvType:
    Type: String
    Description: "The deployment environment: staging, prod, etc."
  AZ1:
    Description: First AZ
    Type: String
    Default: us-east-2a
  AZ2:
    Description: Second AZ
    Type: String
    Default: us-east-2b
  NamePrefix:
    Description: Name prefix for stacks
    Type: String
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair to support SSH access

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        EnvType: !Ref EnvType
        AZ1: !Ref AZ1
        AZ2: !Ref AZ2

  ECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ecr.yaml
      Parameters:
        EnvType: !Ref EnvType
        RepoName: !Ref NamePrefix

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        EnvType: !Ref EnvType
        AZ1: !Ref AZ1
        ClusterIdentifier: !Ref NamePrefix
        VPC: !GetAtt VPCStack.Outputs.VPC
        Subnet1: !GetAtt VPCStack.Outputs.Subnet1
        Subnet2: !GetAtt VPCStack.Outputs.Subnet2

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: compute.yaml
      Parameters:
        EnvType: !Ref EnvType
        VPC: !GetAtt VPCStack.Outputs.VPC
        Subnet1: !GetAtt VPCStack.Outputs.Subnet1
        Subnet2: !GetAtt VPCStack.Outputs.Subnet2
        KeyPair: !Ref KeyPair
        DatabaseSecurityGroup: !GetAtt RDSStack.Outputs.AccessSecurityGroup
